# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.
services:
  sneakershopapi:
    image: sneakershopapi:latest
    build:
      context: ../.
      dockerfile: ../Dockerfile
    ports:
      - 5050:5050
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
